import './globals.css';

import type { Metadata } from 'next';
import { ReactElement, ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * The root layout that wraps all route component.
 * @param {Readonly<{ children: ReactNode }>} props - The component props of the layout.
 * @returns {ReactElement} The rendered layout and it's children.
 */
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>): ReactElement {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
